name: 'action-webhook'
description: 'Send a message to a webhook'
author: 'chrislennon'
inputs:
  message:
    description: 'message to send'
  webhook:
    description: 'webhook URL'
  debug:
    description: 'Enable debug output - *MUST* also set secret ACTIONS_STEP_DEBUG to "true"'
    default: false
runs:
  using: 'node12'
  main: 'lib/main.js'
